### ISSUE TITLE
UTF-8 File append or getContents() Problem.

### ISSUE THREAD

**Issue by mesutcakir** [colinmathews/s3-append#1]
C:\Backups\S3\node_modules\s3-append\node_modules\aws-sdk\lib\request.js:31
            throw err;
            ^

SyntaxError: Unexpected token ﻿
    at Object.parse (native)
    at S3Append.onRead (C:\Backups\S3\node_modules\s3-append\dist\lib\services\s3-append.js:136:44)
    at Response.<anonymous> (C:\Backups\S3\node_modules\s3-append\dist\lib\services\s3-append.js:126:23)
    at Request.<anonymous> (C:\Backups\S3\node_modules\s3-append\node_modules\aws-sdk\lib\request.js:355:18)
    at Request.callListeners (C:\Backups\S3\node_modules\s3-append\node_modules\aws-sdk\lib\sequential_executor.js:105:20)
    at Request.emit (C:\Backups\S3\node_modules\s3-append\node_modules\aws-sdk\lib\sequential_executor.js:77:10)
    at Request.emit (C:\Backups\S3\node_modules\s3-append\node_modules\aws-sdk\lib\request.js:615:14)
    at Request.transition (C:\Backups\S3\node_modules\s3-append\node_modules\aws-sdk\lib\request.js:22:10)
    at AcceptorStateMachine.runTo (C:\Backups\S3\node_modules\s3-append\node_modules\aws-sdk\lib\state_machine.js:14:12)
    at C:\Backups\S3\node_modules\s3-append\node_modules\aws-sdk\lib\state_machine.js:26:10

**Comment by mesutcakir** [comment]
I have a fixed problem code.

S3Append.prototype.onRead = function (contents) {
        this.readDate = new Date();
        this.contents = contents;
        if (this.format === format_1.default.Json) {
            if (contents) {
                **if (eval(contents)) {**
                    this.contentsAsJson = JSON.parse(contents);
                } else {
                    this.contentsAsJson = [];
                }
            }
            else {
                this.contentsAsJson = [];
            }
        }
    };
